### ISSUE TITLE
New Feature: Command Summary

### ISSUE THREAD

**Issue by Holonium** [Stetsed/framework-power-measurment#1]
A feature that may be worth adding could be something like at the end of a run, getting a summary, such as:
`Run time: 00:30:10, Mode: Stress, Threads:8, Average Usage: 32 W, Saved to:./measure/stress8.csv`
I could see it being especially useful for testing long term power consumption of things like expansion cards.

**Comment by Stetsed** [comment]
Will get to work on it

**Comment by Stetsed** [comment]
Added in latest commit 295504b5446b5455032db144ceb0237e0050755b
